### PR TITLE
Add a null filter to re-enable frame count

### PR DESCRIPTION
**Pull request by tvercaut**
This aims at addressing https://github.com/imageio/imageio-ffmpeg/issues/99

### CODE REVIEW

**Review by mgorny — APPROVED** [review]
Also confirmed that this patch works well for us. Thanks!

**Comment by almarklein** [comment]
CI fails on one specific test:
https://github.com/imageio/imageio-ffmpeg/blob/9ab981a8d09138fb1b3b814cb4287b705f258ec5/tests/test_io.py#L40-L43

The result is `14.0`, so it fails. I confirmed (in #108) that without the change in this PR, this failure does not happen. So apparently ffmpeg produces a slightly different value, depending on these output args.

Nonetheless, I think its safe to just update theupper bound to ` <= 14.0` in this test.

**Comment by kkoomen** [comment]
I can confirm this fix works for M1/M2 macbooks as well.

**Comment by almarklein** [comment]
@tvercaut could you update the test I referenced in my earlier comment? That should make the tests pass, so we can merge this 🚀

**Comment by kkoomen** [comment]
@almarklein can't you just update the tests? Looks like OP isn't that active.

**Comment by kkoomen** [comment]
@almarklein can you publish a new version pypi version?

**Comment by almarklein** [comment]
done!

**Pull request merged**
